echo "Run the individual tasks using local resources"
echo "-----------------------------------------------"
echo ""
echo "Note: Install fly or download it from concourse ui page and configure it against a running concourse instance before proceeding with next steps"
echo ""
echo "Run the build task first to build and save the wildcard plugin"
echo "Running tasks using fly would use local resources as opposed to use real (git or s3) for pipeline."
echo "Running the build task"
echo "'build' task requires as input the repository path in form of repo variable"
echo ""
echo "fly execute -c ./scripts/build/task.yml --i repo=../ --privileged"
echo "Save the tar ball under <repo>/binaries folder either in s3 or locally from the build task"
echo ""
echo "Run the test task once build task is successful and there is a tar ball "
echo "     containing the plugin executable for each platform under 'binaries'"
echo "fly execute -c ./scripts/test/task.yml --i repo=../ --privileged \\"
echo "                                          --i binaries=../binaries"
echo ""
echo "There can be additional overrides of the cf and other parameters"
echo "Example: "
echo "fly execute -c ./scripts/test/task.yml                   \\"
echo "                      --privileged                       \\"
echo "                      --i repo=../                       \\"
echo "                      --i binaries=../binaries           \\"
echo "                      binary-name=wildcard               \\"
echo "                      binary-version=0.0.9               \\"
echo "                      binary-bucket=cf-wildcard-plugin   \\"
echo "                      cf_api_endpoint=api.run.pivotal.io \\"
echo "                      cf_user=testuser@xyz.com           \\"
echo "                      cf_password=samplexyz              \\"
echo "                      cf_org=test-org                    \\"
echo "                      cf_space=test-space "
echo ""
